# Google Cloud Build Configuration Template
# Customize this file for your project's build and deployment needs

substitutions:
  # Default substitutions (can be overridden)
  _SERVICE_NAME: 'my-project-api'
  _REGION: 'us-central1'
  _MEMORY: '2Gi'
  _CPU: '2'
  _TIMEOUT: '600'
  _MAX_INSTANCES: '10'
  _CONCURRENCY: '80'
  _ALLOW_UNAUTHENTICATED: 'true'

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: 1800s  # 30 minutes, adjust based on your build complexity

  # Step 2: Push the tagged container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # Step 4: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated=${_ALLOW_UNAUTHENTICATED}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      # Add environment variables (customize based on your needs)
      # - '--set-env-vars'
      # - 'LOG_LEVEL=info,NODE_ENV=production'
      # Add secrets if needed
      # - '--set-secrets'
      # - 'DATABASE_URL=database-url:latest'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Build timeout
timeout: 2400s  # 40 minutes total

# Build options
options:
  machineType: 'E2_HIGHCPU_8'  # Adjust based on your build requirements
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
  # Enable parallel builds for faster execution
  # substitutionOption: ALLOW_LOOSE
