#!/usr/bin/env python3
"""
Interactive setup wizard for ChipaPocketOptionData.
Helps users configure their first data collection setup.
"""

import os
import sys
from pathlib import Path


def print_header(title):
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f" {title}")
    print("=" * 60 + "\n")


def print_step(number, title):
    """Print a step header."""
    print(f"\n{'─' * 60}")
    print(f"Step {number}: {title}")
    print('─' * 60)


def create_env_file():
    """Create .env file with user's SSIDs."""
    print_step(1, "Configure Demo Account SSIDs")
    
    print("\nYou'll need SSIDs from PocketOption demo accounts.")
    print("See docs/HOW_TO_GET_SSID.md for instructions.\n")
    
    show_instructions = input("Show SSID extraction instructions? (y/n): ").lower()
    
    if show_instructions == 'y':
        print("\n" + "─" * 60)
        print("Quick Instructions:")
        print("─" * 60)
        print("1. Go to https://pocketoption.com")
        print("2. Create/login to a demo account")
        print("3. Press F12 to open DevTools")
        print("4. Go to Application → Cookies")
        print("5. Find 'ssid' cookie and copy its value")
        print("6. Repeat for 2-3 more demo accounts")
        print("─" * 60 + "\n")
    
    ssids = []
    print("Enter your demo account SSIDs (press Enter without text when done):")
    
    i = 1
    while True:
        ssid = input(f"  SSID #{i}: ").strip()
        if not ssid:
            break
        ssids.append(ssid)
        i += 1
    
    if not ssids:
        print("\n⚠️  No SSIDs provided. You can add them later to .env file.")
        return False
    
    # Create .env file
    env_path = Path(".env")
    with open(env_path, "w") as f:
        f.write("# PocketOption Demo Account SSIDs\n")
        f.write("# Generated by setup wizard\n\n")
        for i, ssid in enumerate(ssids, 1):
            f.write(f"POCKETOPTION_SSID_{i}={ssid}\n")
        
        f.write("\n# Application Configuration\n")
        f.write("LOG_LEVEL=INFO\n")
        f.write("LOG_PATH=./logs\n")
        f.write("DATA_DB_PATH=./pocketoption_data.db\n")
    
    print(f"\n✅ Created .env file with {len(ssids)} SSID(s)")
    return True


def configure_proxies():
    """Configure proxy settings."""
    print_step(2, "Configure Proxy Support (Optional)")
    
    print("\nProxies help distribute connections and avoid rate limiting.")
    print("You can skip this and add proxies later if needed.\n")
    
    use_proxies = input("Configure proxies now? (y/n): ").lower()
    
    if use_proxies != 'y':
        print("Skipping proxy configuration.")
        return False
    
    print("\nSee docs/PROXY_SETUP.md for proxy service recommendations.\n")
    
    proxies = []
    i = 1
    while True:
        print(f"\nProxy #{i}")
        host = input("  Host (or Enter to finish): ").strip()
        if not host:
            break
        
        port = input("  Port [8080]: ").strip() or "8080"
        username = input("  Username (optional): ").strip()
        password = input("  Password (optional): ").strip()
        protocol = input("  Protocol [http]: ").strip() or "http"
        
        proxy_config = {
            'host': host,
            'port': port,
            'username': username,
            'password': password,
            'protocol': protocol
        }
        proxies.append(proxy_config)
        i += 1
    
    if not proxies:
        print("\nNo proxies configured.")
        return False
    
    # Append to .env
    env_path = Path(".env")
    with open(env_path, "a") as f:
        f.write("\n# Proxy Configuration\n")
        for i, proxy in enumerate(proxies, 1):
            f.write(f"PROXY_HOST_{i}={proxy['host']}\n")
            f.write(f"PROXY_PORT_{i}={proxy['port']}\n")
            if proxy['username']:
                f.write(f"PROXY_USER_{i}={proxy['username']}\n")
            if proxy['password']:
                f.write(f"PROXY_PASS_{i}={proxy['password']}\n")
            f.write(f"PROXY_PROTOCOL_{i}={proxy['protocol']}\n")
    
    print(f"\n✅ Configured {len(proxies)} proxy(ies)")
    return True


def create_example_script():
    """Create a basic example script."""
    print_step(3, "Create Example Script")
    
    print("\nI'll create a basic script to get you started.\n")
    
    script_name = input("Script filename [my_collector.py]: ").strip() or "my_collector.py"
    
    # Read SSIDs from .env if it exists
    ssid_count = 0
    if Path(".env").exists():
        with open(".env") as f:
            ssid_count = sum(1 for line in f if line.startswith("POCKETOPTION_SSID_"))
    
    # Generate script
    script_content = '''"""
Data collection script for PocketOption.
Generated by ChipaPocketOptionData setup wizard.
"""

import os
from dotenv import load_dotenv
from ChipaPocketOptionData import subscribe_symbol_timed

# Load environment variables
load_dotenv()

# Load SSIDs from .env
ssids = [
'''
    
    for i in range(1, ssid_count + 1):
        script_content += f"    os.getenv('POCKETOPTION_SSID_{i}'),\n"
    
    script_content += ''']

# Remove None values (missing SSIDs)
ssids = [s for s in ssids if s]

if not ssids:
    print("❌ No SSIDs found in .env file!")
    print("Please add your SSIDs to the .env file and try again.")
    exit(1)

print(f"Starting data collection with {len(ssids)} account(s)...")

# Create collector
collector = subscribe_symbol_timed(
    asset="EURUSD_otc",
    time_delta=5,  # 5-second candles
    ssids=ssids,
    proxy_support=False,  # Set to True if using proxies
    log_level="INFO"
)

# Collect and display data
try:
    candle_count = 0
    for candle in collector:
        if 'error' in candle:
            print(f"⚠️  Error from {candle['ssid']}: {candle['error']}")
            continue
        
        # Display candle data
        print(f"Candle #{candle_count + 1}: "
              f"Close={candle.get('close'):.5f}, "
              f"High={candle.get('high'):.5f}, "
              f"Low={candle.get('low'):.5f}")
        
        candle_count += 1
        
        # Show progress every 10 candles
        if candle_count % 10 == 0:
            print(f"✓ Collected {candle_count} candles so far...")

except KeyboardInterrupt:
    print("\\n\\nStopping collection...")
finally:
    collector.stop()
    print(f"\\n✅ Collection stopped. Total candles: {candle_count}")
'''
    
    # Write script
    with open(script_name, "w") as f:
        f.write(script_content)
    
    print(f"\n✅ Created {script_name}")
    print(f"\nTo run it:")
    print(f"  python {script_name}")
    
    return script_name


def print_next_steps(script_name):
    """Print next steps for the user."""
    print_header("Setup Complete! 🎉")
    
    print("Your ChipaPocketOptionData setup is ready!\n")
    
    print("Next steps:")
    print(f"  1. Run your collection script:")
    print(f"     python {script_name}\n")
    
    print("  2. Check out the examples:")
    print("     cd examples/")
    print("     python basic_usage.py\n")
    
    print("  3. Read the documentation:")
    print("     docs/QUICK_START.md - Quick start guide")
    print("     docs/PROXY_SETUP.md - Proxy configuration")
    print("     docs/HOW_TO_GET_SSID.md - SSID extraction\n")
    
    print("  4. Explore more examples:")
    print("     - examples/with_proxy_support.py")
    print("     - examples/save_to_database.py")
    print("     - examples/multiple_assets.py\n")
    
    print("Need help?")
    print("  - Open an issue: https://github.com/ChipaDevTeam/ChipaPocketOptionData/issues")
    print("  - Read the docs: docs/")
    print("  - Check examples: examples/\n")


def main():
    """Main setup wizard."""
    print_header("ChipaPocketOptionData Setup Wizard")
    
    print("Welcome! This wizard will help you set up ChipaPocketOptionData.")
    print("You can skip any step and configure manually later.\n")
    
    input("Press Enter to continue...")
    
    # Step 1: Create .env file
    has_ssids = create_env_file()
    
    if not has_ssids:
        print("\n⚠️  You'll need to add SSIDs to .env file before collecting data.")
        print("See docs/HOW_TO_GET_SSID.md for instructions.\n")
    
    # Step 2: Configure proxies
    configure_proxies()
    
    # Step 3: Create example script
    script_name = create_example_script()
    
    # Done!
    print_next_steps(script_name)
    
    print("Happy data collecting! 🚀\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
